export type CatalogItem = {
  slug: string;
  title: string;
  label: string;
  summary: string;
  description: string;
  category: string;
  icon: string;
  stats: { value: string; label: string }[];
  deliverables: string[];
  heroImage: string;
  overview: string;
  applications: string[];
  downloadFile?: string;
  previewImage?: string;
  features?: string[];
  tags?: string[];
};

export const SERVICE_CATALOG: CatalogItem[] = [
  {
    slug: "bim-estimating",
    title: "BIM Estimating Services",
    label: "BIM Estimating",
    summary: "Model-based quantity surveys extracted from BIM files and aligned to cost data.",
    description:
      "We pull accurate quantities straight from your BIM model, tie every element to real cost data, and return it in a format you can bid from.",
    category: "Method",
    icon: "account_tree",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Model-based quantity survey", "Cost-aligned summary", "Bid-ready workbook"],
    heroImage: "https://images.unsplash.com/photo-1581094794329-c8112a89af12??w=800&auto=format&fit=crop&q=60",
    overview: "For teams that want BIM-derived quantities without losing control of pricing and scope review.",
    applications: ["Revit models", "Design-build", "Preconstruction", "Quantity survey"],
  },
  {
    slug: "blueprint-estimating",
    title: "Blueprint Estimating",
    label: "Blueprint Estimating",
    summary: "Plan-based takeoffs from architectural drawings, specs, and bid documents.",
    description:
      "Turn your architectural drawings into precise cost estimates. We analyze every detail of your plans and deliver material and labor calculations you can build on.",
    category: "Method",
    icon: "map",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Blueprint takeoff", "Scope notes", "Markup sheets"],
    heroImage: "https://images.unsplash.com/photo-1497366754035-f200968a6e72??w=800&auto=format&fit=crop&q=60",
    overview: "For contractors who need detailed plan reading and a clean estimate package from drawings alone.",
    applications: ["Bid documents", "Plan sets", "Specs review", "Preconstruction"],
  },
  {
    slug: "budget-estimating",
    title: "Budget Estimating Services",
    label: "Budget Estimating",
    summary: "Conceptual and early-stage project budgets for feasibility and planning.",
    description:
      "From conceptual feasibility budgets to detailed pre-bid cost estimates, we give your project team the financial clarity it needs to move forward.",
    category: "Method",
    icon: "request_quote",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Concept budget", "Early-stage pricing", "Assumption notes"],
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f??w=800&auto=format&fit=crop&q=60",
    overview: "For owners, developers, and teams evaluating a project before full design completion.",
    applications: ["Feasibility", "Early design", "Owner budgets", "Planning"],
  },
  {
    slug: "construction-takeoff",
    title: "Construction Takeoff Services",
    label: "Construction Takeoff",
    summary: "Quantity surveys across CSI trades and building types for bid preparation.",
    description:
      "Every bid you skip because the takeoff was not done is a project you did not win. We deliver accurate quantity surveys for all CSI trades and building types.",
    category: "Method",
    icon: "straighten",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Quantity survey", "Trade breakdown", "Markup plans"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "For busy estimators and contractors who need a fast, complete takeoff package.",
    applications: ["CSI trades", "Bid prep", "General contracting", "Subcontracting"],
  },
  {
    slug: "cost-estimating",
    title: "Cost Estimating Services",
    label: "Cost Estimating",
    summary: "Detailed construction cost estimates for residential, commercial, and industrial work.",
    description:
      "Get accurate construction cost estimates with a 24-48 hour turnaround. We provide expert cost estimation for all project types, all CSI trades, and every construction phase.",
    category: "Method",
    icon: "payments",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Cost model", "Line-item pricing", "Budget summary"],
    heroImage: "https://images.unsplash.com/photo-1518709268805-4e9042af2176??w=800&auto=format&fit=crop&q=60",
    overview: "For projects that need complete pricing instead of just quantities.",
    applications: ["Residential", "Commercial", "Industrial", "Mixed-use"],
  },
  {
    slug: "preliminary-estimate",
    title: "Preliminary Estimate",
    label: "Preliminary Estimate",
    summary: "Conceptual estimate support before the project is fully defined.",
    description:
      "Bad budgets do not start on the job site. They start in a planning meeting where someone approved a number nobody actually verified.",
    category: "Method",
    icon: "timeline",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Concept pricing", "Assumption sheet", "Budget range"],
    heroImage: "https://images.unsplash.com/photo-1486325212027-8081e485255e??w=800&auto=format&fit=crop&q=60",
    overview: "For early-stage planning when scope is still being defined.",
    applications: ["Feasibility", "Planning", "Programming", "Early budgets"],
  },
  {
    slug: "drywall-takeoff",
    title: "Drywall Estimating Services",
    label: "Drywall Takeoff",
    summary: "Division 09 drywall and metal framing estimates with fast, bid-ready delivery.",
    description:
      "Drywall takeoffs done right, every time. We handle the full Division 09 scope for busy contractors, from gypsum board and metal framing through finish levels and specialty assemblies.",
    category: "Finishes",
    icon: "layers",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: [
      "Gypsum board and framing quantities",
      "Finish level and accessories breakdown",
      "Excel and PDF estimate package",
    ],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview:
      "Built for drywall subcontractors, general contractors, and project managers who need an organized estimate that can be dropped straight into a bid package.",
    applications: ["Commercial interiors", "Healthcare fit-outs", "Tenant improvements", "Multi-family projects"],
  },
  {
    slug: "flooring-estimating",
    title: "Flooring Estimating Services",
    label: "Flooring Estimating",
    summary: "Tile, carpet, hardwood, and resilient flooring takeoffs with labor and waste factors included.",
    description:
      "Wrong waste factors and missed transitions cause jobs to bleed margin. We build flooring estimates from the actual drawings so you can bid with confidence.",
    category: "Finishes",
    icon: "grid_on",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "97%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Room-by-room area breakdown", "Waste and transition allowances", "Material and labor schedule"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview:
      "Accurate flooring takeoffs for installers, finish subcontractors, and GC teams managing high-volume interiors.",
    applications: ["Commercial interiors", "Retail fit-outs", "Hospitality", "Residential remodels"],
  },
  {
    slug: "insulation-estimating",
    title: "Insulation Estimating Services",
    label: "Insulation Estimating",
    summary: "Thermal and acoustic insulation estimates that stay aligned with specs and site conditions.",
    description:
      "Wrong insulation quantities do not show up until you are reordering mid-project. We prevent that by pricing batt, blown, spray foam, and specialty assemblies from the start.",
    category: "Finishes",
    icon: "ac_unit",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Thermal and acoustic quantities", "R-value and assembly notes", "Excel line-item summary"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview:
      "Made for insulation contractors and GCs that need fast estimates without losing visibility into spec-driven scope.",
    applications: ["Commercial buildings", "Exterior walls", "Mechanical rooms", "Multi-family projects"],
  },
  {
    slug: "interior-and-exterior-finishes-estimating",
    title: "Interior & Exterior Finishes Estimating Services",
    label: "Finishes Estimating",
    summary: "A full finishes scope covering coatings, wall systems, and exterior envelope work.",
    description:
      "We support flooring, painting, ceiling, drywall, and envelope-related finishes with a clean deliverable that keeps the scope organized and reviewable.",
    category: "Finishes",
    icon: "format_paint",
    stats: [
      { value: "All", label: "Finish Types" },
      { value: "24-48h", label: "Turnaround" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Finish schedule and quantities", "Labor and material summary", "PDF markup sheets"],
    heroImage: "https://images.unsplash.com/photo-1484154218962-a197022b5858??w=800&auto=format&fit=crop&q=60",
    overview:
      "A combined finishes workflow for contractors who want one coordinated estimate across multiple interior and exterior scopes.",
    applications: ["Tenant improvements", "Retail", "Hospitality", "Renovation work"],
  },
  {
    slug: "millwork-estimating",
    title: "Millwork Estimating Services",
    label: "Millwork Estimating",
    summary: "Cabinetry, casework, and architectural woodwork estimates built from the actual drawings.",
    description:
      "A sloppy carpentry estimate costs you the job or the money once you are on site. We quantify materials, shop labor, field installation, hardware, and waste factors.",
    category: "Finishes",
    icon: "chair",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "CSI", label: "Format" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Shop and field labor breakdown", "Hardware and finish schedules", "Material takeoff workbook"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview:
      "Built for millwork shops and carpentry contractors who need tightly scoped pricing and clean presentation sheets.",
    applications: ["Custom cabinetry", "Casework", "Architectural woodwork", "Commercial interiors"],
  },
  {
    slug: "openings-estimating",
    title: "Doors, Windows & Openings Estimating Services",
    label: "Openings Estimating",
    summary: "Door, window, and hardware estimating with schedule-driven quantity control.",
    description:
      "Missed items on an openings estimate do not show up until the job is already underway. We keep doors, frames, hardware, and glazing aligned before bid day.",
    category: "Finishes",
    icon: "door_open",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "CSI", label: "Format" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Door and frame schedule", "Hardware and glazing counts", "Bid-ready summary sheet"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview:
      "For contractors and suppliers who need opening quantities organized by schedule, type, and finish.",
    applications: ["Commercial buildings", "Schools", "Hospitals", "Retail centers"],
  },
  {
    slug: "painting-estimating",
    title: "Painting Estimating Services",
    label: "Painting Estimating",
    summary: "Interior and exterior painting estimates with coverage rates, surface prep, and coatings included.",
    description:
      "Surface prep miscalculations and missed coating requirements can turn a profitable painting job into a loss. We build the scope before the first roller touches the wall.",
    category: "Finishes",
    icon: "brush",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Coverage and prep breakdown", "Interior and exterior finish quantities", "Labor and coating summary"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview:
      "Designed for painting subcontractors and GCs bidding tenant improvements, remodels, and exterior repaint scopes.",
    applications: ["Commercial repaint", "Interior fit-out", "Exterior coatings", "Industrial maintenance"],
  },
  {
    slug: "duct-estimating",
    title: "Duct Estimating Services",
    label: "Duct Estimating",
    summary: "HVAC ductwork estimates covering fittings, accessories, insulation, and hangers.",
    description:
      "You are already running jobs and chasing bids. The last thing you need is hours spent on ductwork takeoffs that may not even win. We handle the scope and pricing for you.",
    category: "MEP",
    icon: "air",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Duct, fitting, and accessory counts", "Insulation and hanger schedule", "Mechanical summary workbook"],
    heroImage: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5??w=800&auto=format&fit=crop&q=60",
    overview:
      "For HVAC contractors and mechanical teams that need a fast, accurate package ready for bid submission.",
    applications: ["Commercial HVAC", "Healthcare", "Industrial systems", "Tenant improvements"],
  },
  {
    slug: "commercial-estimating",
    title: "Commercial Estimating",
    label: "Commercial",
    summary: "Office, retail, hospitality, and mixed-use estimating for contractor bids.",
    description:
      "Most commercial contractors lose bids not because they are bad at their job, but because their numbers are off. We handle the pricing so you can focus on the project.",
    category: "Project Type",
    icon: "business",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Commercial scope breakdown", "Trade pricing summary", "Bid-ready workbook"],
    heroImage: "https://images.unsplash.com/photo-1486325212027-8081e485255e??w=800&auto=format&fit=crop&q=60",
    overview: "For office, retail, hospitality, and mixed-use projects requiring coordinated pricing.",
    applications: ["Office", "Retail", "Hospitality", "Mixed-use"],
  },
  {
    slug: "green-building",
    title: "Green Building Estimating",
    label: "Green Building",
    summary: "LEED, Energy Star, BREEAM, and sustainable project cost estimates.",
    description:
      "Green buildings cost more upfront. We provide accurate green construction estimating for certification-driven projects with current market pricing.",
    category: "Project Type",
    icon: "eco",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Sustainable scope pricing", "Certification notes", "Budget summary"],
    heroImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e??w=800&auto=format&fit=crop&q=60",
    overview: "For teams pursuing sustainable construction targets and certification programs.",
    applications: ["LEED", "Energy Star", "BREEAM", "Green projects"],
  },
  {
    slug: "industrial-estimating",
    title: "Industrial Estimating",
    label: "Industrial",
    summary: "Manufacturing, warehouse, and process-facility estimating built for complex jobs.",
    description:
      "Industrial projects do not forgive bad estimates. Get the numbers wrong and you are either eating the loss or losing the bid. We fix that.",
    category: "Project Type",
    icon: "factory",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Industrial scope breakdown", "Equipment summary", "Cost workbook"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "For manufacturing, process, and warehouse work where scope control matters.",
    applications: ["Manufacturing", "Warehouses", "Process plants", "Distribution"],
  },
  {
    slug: "renovation-estimating",
    title: "Renovation Estimating",
    label: "Renovation",
    summary: "Renovation, remodeling, and adaptive reuse estimating for existing buildings.",
    description:
      "Full cost estimation for renovation, remodeling, and adaptive reuse projects with the unique challenges of working in existing buildings accounted for.",
    category: "Project Type",
    icon: "build",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Renovation scope breakdown", "Demolition allowances", "Pricing workbook"],
    heroImage: "https://images.unsplash.com/photo-1484154218962-a197022b5858??w=800&auto=format&fit=crop&q=60",
    overview: "For remodeling and adaptive reuse projects where existing conditions matter.",
    applications: ["Remodels", "Adaptive reuse", "Tenant improvements", "Retrofits"],
  },
  {
    slug: "residential-estimating",
    title: "Residential Estimating",
    label: "Residential",
    summary: "Single-family, townhome, and multifamily estimating for builders and contractors.",
    description:
      "You are busy managing crews and chasing subs. We handle the residential estimating side so you can stay focused on what actually makes you money.",
    category: "Project Type",
    icon: "home",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Residential scope summary", "Trade pricing", "Bid-ready package"],
    heroImage: "https://images.unsplash.com/photo-1570129477492-45c003edd2be??w=800&auto=format&fit=crop&q=60",
    overview: "For residential teams that need clean pricing on tight timelines.",
    applications: ["Single-family", "Townhomes", "Multifamily", "Custom homes"],
  },
  {
    slug: "building-cost-estimating",
    title: "Building Cost Estimating",
    label: "Building Cost Estimating",
    summary: "Full building cost estimates from order-of-magnitude through bid stage.",
    description:
      "Full building cost estimates for every type of construction. Professional quantity takeoffs and detailed cost analysis from order of magnitude through bid estimates.",
    category: "Specialty",
    icon: "domain_add",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Building-level cost model", "Trade summary", "Bid package"],
    heroImage: "https://images.unsplash.com/photo-1518709268805-4e9042af2176??w=800&auto=format&fit=crop&q=60",
    overview: "For full-building pricing across project types and stages.",
    applications: ["Concept to bid", "Full building scopes", "Owner budgets", "General contractors"],
  },
];

export const TRADE_CATALOG: CatalogItem[] = [
  {
    slug: "mep-estimating",
    title: "MEP Estimating",
    label: "MEP",
    summary: "Mechanical, electrical, and plumbing estimates across all project types.",
    description:
      "Mechanical, electrical, and plumbing scopes are where mistakes become expensive. We keep the pricing coordinated across trades so your bid holds together.",
    category: "MEP",
    icon: "engineering",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Combined MEP summary", "Trade-by-trade breakdown", "PDF markup set"],
    heroImage: "https://images.unsplash.com/photo-1581094794329-c8112a89af12??w=800&auto=format&fit=crop&q=60",
    overview:
      "A coordinated estimate package for projects that need one source of truth across mechanical, electrical, and plumbing scope.",
    applications: ["Commercial buildings", "Institutional work", "Industrial facilities", "Mixed-use projects"],
  },
  {
    slug: "electrical-estimating",
    title: "Electrical Estimating",
    label: "Electrical",
    summary: "Power, lighting, and low-voltage electrical takeoffs with clean line-item organization.",
    description:
      "We provide professional electrical estimating services for contractors and builders across all states, delivered in Excel and PDF with the scope organized for review.",
    category: "MEP",
    icon: "bolt",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Lighting and power counts", "Panel and circuit summaries", "Low-voltage allowance sheet"],
    heroImage: "https://images.unsplash.com/photo-1518709268805-4e9042af2176??w=800&auto=format&fit=crop&q=60",
    overview: "For electrical contractors who need accurate counts and a bid format that is simple to review and price.",
    applications: ["Commercial", "Retail", "Healthcare", "Tenant fit-outs"],
  },
  {
    slug: "hvac-estimating",
    title: "HVAC Estimating",
    label: "HVAC",
    summary: "HVAC equipment, ductwork, and system scope estimates priced to your market.",
    description:
      "Bad numbers cost you jobs. We handle the HVAC takeoff so you can focus on winning work without carrying hidden scope risk.",
    category: "MEP",
    icon: "ac_unit",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Equipment schedule", "Duct and accessory counts", "Mechanical labor summary"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "Built for HVAC contractors bidding new work, retrofits, and tenant improvement packages.",
    applications: ["Commercial HVAC", "Mechanical rooms", "Retrofits", "Multi-family"],
  },
  {
    slug: "mechanical-estimating",
    title: "Mechanical Estimating",
    label: "Mechanical",
    summary: "Mechanical, piping, and plumbing estimates with scope clarity built in.",
    description:
      "Mechanical work can represent a major share of total project cost. We keep pipe, equipment, and system quantities aligned so the number is defensible.",
    category: "MEP",
    icon: "settings",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Mechanical scope breakdown", "Piping and equipment counts", "Budget summary"],
    heroImage: "https://images.unsplash.com/photo-1514996937319-344454492b37??w=800&auto=format&fit=crop&q=60",
    overview: "For mechanical contractors who need fast pricing without sacrificing scope detail.",
    applications: ["Commercial", "Industrial", "Health care", "Institutional"],
  },
  {
    slug: "piping-estimating",
    title: "Piping Estimating",
    label: "Piping",
    summary: "Piping estimates for process, domestic, mechanical, and specialty systems.",
    description:
      "Piping scopes look manageable on paper until the wrong pressure rating gets priced or a line item gets missed. We solve that before bid day.",
    category: "MEP",
    icon: "plumbing",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Pipe schedule", "Fitting counts", "Labor summary"],
    heroImage: "https://images.unsplash.com/photo-1514996937319-344454492b37??w=800&auto=format&fit=crop&q=60",
    overview: "For contractors handling process and mechanical pipe scope.",
    applications: ["Process piping", "Mechanical piping", "Domestic water", "Specialty systems"],
  },
  {
    slug: "metals-estimating",
    title: "Metals Estimating",
    label: "Metals",
    summary: "Structural and miscellaneous metals takeoffs for bid and fabrication review.",
    description:
      "Get accurate structural steel and miscellaneous metals takeoffs for all construction projects with shop and erection scope clearly separated.",
    category: "Structure",
    icon: "hexagon",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Metal schedule", "Fabrication notes", "Erection breakdown"],
    heroImage: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6??w=800&auto=format&fit=crop&q=60",
    overview: "For steel fabricators and misc metals contractors who need a complete scope package.",
    applications: ["Structural steel", "Miscellaneous metals", "Fabrication", "Erection"],
  },
  {
    slug: "plumbing-estimating",
    title: "Plumbing Estimating",
    label: "Plumbing",
    summary: "Domestic water, sanitary, storm, and fixture estimates for all project types.",
    description:
      "Plumbing drawings look straightforward until routing, fixture counts, gas systems, and tie-ins start stacking up. We quantify the full scope before bid day.",
    category: "MEP",
    icon: "plumbing",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Fixture schedule", "Piping and fitting counts", "Material takeoff workbook"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview: "For plumbing contractors and GC teams that need a clean, reviewable takeoff package.",
    applications: ["Commercial plumbing", "Residential developments", "Healthcare", "Schools"],
  },
  {
    slug: "concrete-estimating",
    title: "Concrete Estimating",
    label: "Concrete",
    summary: "Foundations, slabs, walls, and structural concrete takeoffs with reinforcing scope support.",
    description:
      "We provide professional concrete estimating services and concrete takeoff services for contractors and builders across all states.",
    category: "Structure",
    icon: "foundation",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Slab and foundation quantities", "Reinforcement summary", "Concrete placement notes"],
    heroImage: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6??w=800&auto=format&fit=crop&q=60",
    overview: "For concrete contractors managing structural, foundation, and site concrete scope.",
    applications: ["Foundations", "Slabs", "Walls", "Structural concrete"],
  },
  {
    slug: "lumber-estimating",
    title: "Lumber Estimating",
    label: "Lumber",
    summary: "Framing, lumber, and wood structure estimates for residential and commercial work.",
    description:
      "Ordering too much lumber wastes money and ordering too little stalls the job. We keep framing quantities aligned to the actual build plan.",
    category: "Structure",
    icon: "bedroom_child",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Stud and framing counts", "Sheathing and fastening allowance", "Summary workbook"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "For framers and builders who need a takeoff that matches the framing plan instead of a guess.",
    applications: ["Residential framing", "Commercial framing", "Additions", "Wood structures"],
  },
  {
    slug: "masonry-estimating",
    title: "Masonry Estimating",
    label: "Masonry",
    summary: "Brick, block, and stone estimates organized for field and bid review.",
    description:
      "Bad numbers cost you jobs. Masonry work needs a takeoff that captures every unit, accessory, and reinforcement item before pricing starts.",
    category: "Structure",
    icon: "domain",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Unit count and area breakdown", "Mortar and reinforcement schedule", "Material summary"],
    heroImage: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5??w=800&auto=format&fit=crop&q=60",
    overview: "Built for masonry contractors bidding commercial, institutional, and residential scopes.",
    applications: ["Brick", "Block", "Stone", "Structural masonry"],
  },
  {
    slug: "steel-estimating",
    title: "Steel Estimating",
    label: "Steel",
    summary: "Structural steel and miscellaneous metals estimates with shop and erection scope separated.",
    description:
      "Wrong steel numbers cost you the bid or the margin. We keep fabrication, erection, and connection scope clear so the pricing is defensible.",
    category: "Structure",
    icon: "construction",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Weight and tonnage schedule", "Connection scope notes", "Shop and erection breakdown"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "For steel fabricators and erectors that need scope clarity before pricing and bidding.",
    applications: ["Structural steel", "Miscellaneous metals", "Fabrication", "Erection"],
  },
  {
    slug: "rebar-estimating",
    title: "Rebar Estimating",
    label: "Rebar",
    summary: "Reinforcing steel takeoffs and bar schedules for concrete structures.",
    description:
      "We quantify reinforcing steel from your structural drawings so bar schedules, lengths, and placements are ready before the bid goes out.",
    category: "Structure",
    icon: "straighten",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Bar bending schedule", "Placement summary", "Weight breakdown"],
    heroImage: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6??w=800&auto=format&fit=crop&q=60",
    overview: "For reinforcing contractors and concrete teams that need precise bar quantities and bending details.",
    applications: ["Foundations", "Walls", "Slabs", "Structural concrete"],
  },
  {
    slug: "roofing-estimating",
    title: "Roofing Estimating",
    label: "Roofing",
    summary: "Commercial roofing estimates covering membrane, shingles, metal, and waterproofing systems.",
    description:
      "Roofing mistakes do not show up until the job is already underway. We prevent budget overruns by quantifying the real roof scope before you bid.",
    category: "Site",
    icon: "roofing",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Roof area and slope breakdown", "Flashing and accessory counts", "Summary sheet"],
    heroImage: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df??w=800&auto=format&fit=crop&q=60",
    overview: "For roofing contractors who need fast, organized takeoffs that support a tight bid.",
    applications: ["Flat roofing", "Metal roofing", "Shingle systems", "Waterproofing"],
  },
  {
    slug: "thermal-and-moisture-protection-estimating",
    title: "Thermal & Moisture Protection",
    label: "Thermal & Moisture",
    summary: "Waterproofing, dampproofing, insulation, and fireproofing-related protection scopes.",
    description:
      "Moisture protection estimating is where budgets quietly fall apart. We keep the thermal and moisture scope organized so the pricing holds on site.",
    category: "Site",
    icon: "water_drop",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "96%", label: "Accuracy" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Waterproofing quantities", "Insulation and membrane summary", "Protection scope notes"],
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f??w=800&auto=format&fit=crop&q=60",
    overview: "Built for specialty contractors handling envelope protection and insulation-related scopes.",
    applications: ["Waterproofing", "Dampproofing", "Insulation", "Envelope protection"],
  },
  {
    slug: "fireproofing-estimating",
    title: "Fireproofing Estimating",
    label: "Fireproofing",
    summary: "Sprayed fire-resistive material and intumescent coating takeoffs for structural elements.",
    description:
      "Fireproofing numbers need to be tight. We build estimates from your structural drawings so the coverage, thickness, and scope stay aligned.",
    category: "Site",
    icon: "local_fire_department",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Structural coverage schedule", "Thickness and area summary", "Bid-ready workbook"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "For fireproofing contractors and project teams pricing structural protection scope.",
    applications: ["SFRM", "Intumescent coating", "Commercial steel", "Industrial structures"],
  },
  {
    slug: "gutter-estimating",
    title: "Gutter Estimating",
    label: "Gutter",
    summary: "Gutter and downspout estimates for residential and commercial projects.",
    description:
      "We estimate gutter and drainage systems for all building types with clear counts and material quantities.",
    category: "Site",
    icon: "waterfall_chart",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "PDF", label: "Delivery" },
    ],
    deliverables: ["Run and downspout lengths", "Accessory schedule", "Material summary"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview: "For gutter contractors and builders needing fast drainage scope pricing.",
    applications: ["Residential", "Commercial", "Drainage systems", "Retrofits"],
  },
  {
    slug: "landscaping-estimating",
    title: "Landscaping Estimating",
    label: "Landscaping",
    summary: "Plants, hardscape, irrigation, and site beautification estimates for exterior scopes.",
    description:
      "We deliver landscaping estimates in 24-48 hours so your team can focus on the build instead of line-by-line counting.",
    category: "Site",
    icon: "grass",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Plant and hardscape schedule", "Irrigation quantities", "Sitework summary"],
    heroImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef??w=800&auto=format&fit=crop&q=60",
    overview: "For landscaping contractors bidding commercial, residential, and public realm scopes.",
    applications: ["Planting", "Hardscape", "Irrigation", "Site beautification"],
  },
  {
    slug: "sitework-estimating",
    title: "Sitework Estimating",
    label: "Sitework",
    summary: "Grading, excavation, utilities, and earthwork estimates for development projects.",
    description:
      "Site contractors and developers rely on us for accurate sitework estimates, cut and fill takeoffs, and 3D map support.",
    category: "Site",
    icon: "terrain",
    stats: [
      { value: "24-48h", label: "Turnaround" },
      { value: "Zip", label: "Pricing" },
      { value: "Excel", label: "Delivery" },
    ],
    deliverables: ["Cut/fill quantities", "Utility and paving summary", "Grading scope sheet"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "For earthwork and site contractors who need fast preconstruction support on heavy civil scopes.",
    applications: ["Grading", "Excavation", "Utilities", "Site development"],
  },
];

export const SAMPLE_CATALOG: CatalogItem[] = [
  {
    slug: "concrete-sample",
    title: "Concrete Estimating Sample",
    label: "Concrete",
    summary: "Detailed structural and site concrete takeoff including reinforcement.",
    description: "Detailed structural and site concrete takeoff including reinforcement.",
    category: "Structure",
    icon: "foundation",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Quantity summary", "Reinforcement schedule"],
    heroImage: "https://images.unsplash.com/photo-1523413651479-597eb2da0ad6??w=800&auto=format&fit=crop&q=60",
    overview: "Sample concrete estimating package.",
    applications: ["Slabs", "Foundations", "Structural concrete"],
    downloadFile: "/samples/Concrete-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "drywall-sample",
    title: "Drywall Estimating Sample",
    label: "Drywall",
    summary: "Comprehensive drywall and framing takeoff.",
    description: "Comprehensive drywall and framing takeoff for commercial interiors.",
    category: "Finishes",
    icon: "layers",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Gypsum quantities", "Framing counts"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "Sample drywall estimating package.",
    applications: ["Partitions", "Ceilings", "Framing"],
    downloadFile: "/samples/Drywall-sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "electrical-sample",
    title: "Electrical Estimating Sample",
    label: "Electrical",
    summary: "Electrical takeoff covering power, lighting, and low voltage.",
    description: "Electrical takeoff covering power, lighting, and low voltage.",
    category: "MEP",
    icon: "bolt",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Fixture counts", "Cable lengths"],
    heroImage: "https://images.unsplash.com/photo-1518709268805-4e9042af2176??w=800&auto=format&fit=crop&q=60",
    overview: "Sample electrical estimating package.",
    applications: ["Lighting", "Power", "Low Voltage"],
    downloadFile: "/samples/Electrical-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "exterior-sample",
    title: "Exterior Estimating Sample",
    label: "Exterior",
    summary: "Envelope and exterior finishes takeoff.",
    description: "Envelope and exterior finishes takeoff.",
    category: "Site",
    icon: "house",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Facade areas", "Trim quantities"],
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f??w=800&auto=format&fit=crop&q=60",
    overview: "Sample exterior estimating package.",
    applications: ["Siding", "Masonry", "Trim"],
    downloadFile: "/samples/Exterior-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "flooring-sample",
    title: "Flooring Estimating Sample",
    label: "Flooring",
    summary: "Tile, carpet, and resilient flooring takeoff.",
    description: "Tile, carpet, and resilient flooring takeoff.",
    category: "Finishes",
    icon: "grid_on",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Area breakdown", "Base quantities"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview: "Sample flooring estimating package.",
    applications: ["Tile", "Carpet", "LVT"],
    downloadFile: "/samples/Flooring-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "hvac-sample",
    title: "HVAC Estimating Sample",
    label: "HVAC",
    summary: "HVAC equipment and ductwork takeoff.",
    description: "HVAC equipment and ductwork takeoff.",
    category: "MEP",
    icon: "ac_unit",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Equipment schedule", "Ductwork quantities"],
    heroImage: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5??w=800&auto=format&fit=crop&q=60",
    overview: "Sample HVAC estimating package.",
    applications: ["Ductwork", "Equipment", "Piping"],
    downloadFile: "/samples/HVAC-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "insulation-sample",
    title: "Insulation Estimating Sample",
    label: "Insulation",
    summary: "Thermal and acoustic insulation takeoff.",
    description: "Thermal and acoustic insulation takeoff.",
    category: "Finishes",
    icon: "ac_unit",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Coverage areas", "R-value notes"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "Sample insulation estimating package.",
    applications: ["Batt", "Spray Foam", "Rigid"],
    downloadFile: "/samples/Insulation-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "lumber-sample",
    title: "Lumber Estimating Sample",
    label: "Lumber",
    summary: "Wood framing and rough carpentry takeoff.",
    description: "Wood framing and rough carpentry takeoff.",
    category: "Structure",
    icon: "bedroom_child",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Stud counts", "Sheathing areas"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "Sample lumber estimating package.",
    applications: ["Framing", "Decking", "Trusses"],
    downloadFile: "/samples/LUMBER-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "mep-sample",
    title: "MEP Estimating Sample",
    label: "MEP",
    summary: "Combined mechanical, electrical, and plumbing takeoff.",
    description: "Combined mechanical, electrical, and plumbing takeoff.",
    category: "MEP",
    icon: "engineering",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Combined summary", "Trade breakdowns"],
    heroImage: "https://images.unsplash.com/photo-1581094794329-c8112a89af12??w=800&auto=format&fit=crop&q=60",
    overview: "Sample full MEP estimating package.",
    applications: ["Mechanical", "Electrical", "Plumbing"],
    downloadFile: "/samples/MEP-SAMPLE.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "masonry-sample",
    title: "Masonry Estimating Sample",
    label: "Masonry",
    summary: "Brick and block masonry takeoff.",
    description: "Brick and block masonry takeoff.",
    category: "Structure",
    icon: "domain",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Unit counts", "Mortar calculations"],
    heroImage: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5??w=800&auto=format&fit=crop&q=60",
    overview: "Sample masonry estimating package.",
    applications: ["Brick", "CMU", "Stone"],
    downloadFile: "/samples/Masonry-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "mechanical-sample",
    title: "Mechanical Estimating Sample",
    label: "Mechanical",
    summary: "Mechanical systems and piping takeoff.",
    description: "Mechanical systems and piping takeoff.",
    category: "MEP",
    icon: "settings",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Pipe routing", "Equipment notes"],
    heroImage: "https://images.unsplash.com/photo-1514996937319-344454492b37??w=800&auto=format&fit=crop&q=60",
    overview: "Sample mechanical estimating package.",
    applications: ["Piping", "Equipment", "Controls"],
    downloadFile: "/samples/Mechanical-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "mill-work-sample",
    title: "Millwork Estimating Sample",
    label: "Millwork",
    summary: "Custom cabinetry and casework takeoff.",
    description: "Custom cabinetry and casework takeoff.",
    category: "Finishes",
    icon: "chair",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Cabinet schedule", "Countertop areas"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview: "Sample millwork estimating package.",
    applications: ["Casework", "Trim", "Countertops"],
    downloadFile: "/samples/Mill-work-sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "paint-sample",
    title: "Paint Estimating Sample",
    label: "Paint",
    summary: "Interior and exterior painting takeoff.",
    description: "Interior and exterior painting takeoff.",
    category: "Finishes",
    icon: "brush",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Surface areas", "Coating requirements"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "Sample painting estimating package.",
    applications: ["Interior Paint", "Exterior Paint", "Coatings"],
    downloadFile: "/samples/Paint-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "plumbing-sample",
    title: "Plumbing Estimating Sample",
    label: "Plumbing",
    summary: "Plumbing fixtures and piping takeoff.",
    description: "Plumbing fixtures and piping takeoff.",
    category: "MEP",
    icon: "plumbing",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Fixture schedule", "Pipe lengths"],
    heroImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f??w=800&auto=format&fit=crop&q=60",
    overview: "Sample plumbing estimating package.",
    applications: ["Domestic Water", "Sanitary", "Fixtures"],
    downloadFile: "/samples/Plumbing-Sample.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "roofing-sample",
    title: "Roofing Estimating Sample",
    label: "Roofing",
    summary: "Commercial and residential roofing takeoff.",
    description: "Commercial and residential roofing takeoff.",
    category: "Structure",
    icon: "roofing",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Roof areas", "Flashing notes"],
    heroImage: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df??w=800&auto=format&fit=crop&q=60",
    overview: "Sample roofing estimating package.",
    applications: ["Membrane", "Shingles", "Metal Roofs"],
    downloadFile: "/samples/ROOFING-SAMPLE.xlsx",
    previewImage: "/blog_pic.png",
  },
  {
    slug: "sitework-sample",
    title: "Sitework Estimating Sample",
    label: "Sitework",
    summary: "Grading, utilities, and earthwork takeoff.",
    description: "Grading, utilities, and earthwork takeoff.",
    category: "Site",
    icon: "terrain",
    stats: [{ value: "Excel", label: "Format" }, { value: "PDF", label: "Markup" }, { value: "CSI", label: "Standard" }],
    deliverables: ["Cut/Fill summary", "Utility runs"],
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd??w=800&auto=format&fit=crop&q=60",
    overview: "Sample sitework estimating package.",
    applications: ["Grading", "Utilities", "Paving"],
    downloadFile: "/samples/Sitework-Sample.xlsx",
    previewImage: "/blog_pic.png",
  }
];

export const SAMPLE_WORKBOOKS = [
  { title: "Drywall Takeoff Sample", fileName: "Drywall-sample.xlsx", category: "Finishes" },
  { title: "Concrete Estimating Sample", fileName: "Concrete-Sample.xlsx", category: "Structure" },
  { title: "Electrical Estimating Sample", fileName: "Electrical-Sample.xlsx", category: "MEP" },
  { title: "Exterior Estimating Sample", fileName: "Exterior-Sample.xlsx", category: "Site" },
  { title: "Flooring Estimating Sample", fileName: "Flooring-Sample.xlsx", category: "Finishes" },
  { title: "Mechanical Estimating Sample", fileName: "Mechanical-Sample.xlsx", category: "MEP" },
  { title: "Masonry Estimating Sample", fileName: "Masonry-Sample.xlsx", category: "Structure" },
  { title: "Lumber Estimating Sample", fileName: "LUMBER-Sample.xlsx", category: "Structure" },
  { title: "Lumber Estimating Sample 2", fileName: "LUMBER-Sample_2.xlsx", category: "Structure" },
  { title: "Insulation Estimating Sample", fileName: "Insulation-Sample.xlsx", category: "Finishes" },
  { title: "HVAC Estimating Sample", fileName: "HVAC-Sample.xlsx", category: "MEP" },
  { title: "Painting Estimating Sample", fileName: "Paint-Sample.xlsx", category: "Finishes" },
  { title: "Sitework Estimating Sample", fileName: "Sitework-Sample.xlsx", category: "Site" },
  { title: "Millwork Estimating Sample", fileName: "Mill-work-sample.xlsx", category: "Finishes" },
  { title: "MEP Estimating Sample", fileName: "MEP-SAMPLE.xlsx", category: "MEP" },
  { title: "Plumbing Estimating Sample", fileName: "Plumbing-Sample.xlsx", category: "MEP" },
  { title: "Roofing Estimating Sample", fileName: "ROOFING-SAMPLE.xlsx", category: "Structure" },
];

export const CATALOG_BY_SLUG = new Map<string, CatalogItem>([
  ...SERVICE_CATALOG,
  ...TRADE_CATALOG,
  ...SAMPLE_CATALOG,
].map((item) => [item.slug, item]));

export function getCatalogItem(slug: string) {
  return CATALOG_BY_SLUG.get(slug);
}

export function groupCatalogItems(items: CatalogItem[]) {
  return items.reduce<Record<string, CatalogItem[]>>((groups, item) => {
    if (!groups[item.category]) {
      groups[item.category] = [];
    }
    groups[item.category].push(item);
    return groups;
  }, {});
}
