// Site-wide constants for the reference-style construction estimating site

import { SAMPLE_CATALOG, SERVICE_CATALOG, TRADE_CATALOG } from "./catalog";

export const SITE = {
  name: "BluePeak Estimation",
  tagline: "Precision construction estimates delivered fast.",
  description:
    "Professional construction estimating and takeoff services for contractors across all 50 states. Residential, commercial, industrial estimates delivered in 24-48 hours.",
  url: "https://bluepeakestimation.com",
  email: "bluepeakestimation@gmail.com",
  phone: "+1-212-555-0193",
  whatsapp: "+18005550193",
  address: "United States of America",
  businessHours: "Monday – Friday: 8:00 AM – 6:00 PM EST",
  founded: "2015",
};

export const SOCIAL = {
  linkedin: "https://www.linkedin.com/company/bluepeak-estimation",
  facebook: "https://www.facebook.com/bluepeakestimation",
  instagram: "https://www.instagram.com/bluepeakestimation",
  twitter: "https://x.com/bluepeakest",
  youtube: "https://www.youtube.com/@bluepeakestimation",
};

export const STATS = [
  { value: 5000, suffix: "+", label: "Projects Estimated" },
  { value: 98, suffix: "%", label: "Bid Success Rate" },
  { value: 10, suffix: "+", label: "Years Experience" },
  { value: 48, suffix: "h", label: "Avg. Turnaround" },
];

export const SERVICES = [
  ...SERVICE_CATALOG,
  ...TRADE_CATALOG,
  ...SAMPLE_CATALOG,
];

export const INDUSTRIES = [
  {
    slug: "commercial",
    title: "Commercial",
    description: "Office buildings, retail centers, hotels, and mixed-use developments",
    icon: "Building2",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=600&q=80",
  },
  {
    slug: "residential",
    title: "Residential",
    description: "Single-family homes, condominiums, townhouses, and multi-family housing",
    icon: "Home",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=600&q=80",
  },
  {
    slug: "industrial",
    title: "Industrial",
    description: "Warehouses, manufacturing plants, distribution centers, and industrial parks",
    icon: "Factory",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
  },
  {
    slug: "healthcare",
    title: "Healthcare",
    description: "Hospitals, medical centers, outpatient clinics, and healthcare facilities",
    icon: "Heart",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80",
  },
  {
    slug: "education",
    title: "Education",
    description: "Schools, universities, research facilities, and campus buildings",
    icon: "GraduationCap",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80",
  },
  {
    slug: "government",
    title: "Government",
    description: "Federal buildings, courthouses, military facilities, and public infrastructure",
    icon: "Landmark",
    image: "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=600&q=80",
  },
  {
    slug: "infrastructure",
    title: "Infrastructure",
    description: "Bridges, highways, tunnels, airports, and transportation systems",
    icon: "Waypoints",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",
  },
  {
    slug: "retail",
    title: "Retail",
    description: "Shopping centers, strip malls, big-box stores, and retail fit-outs",
    icon: "ShoppingBag",
    image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=600&q=80",
  },
  {
    slug: "energy",
    title: "Energy",
    description: "Power plants, solar farms, wind projects, and utility infrastructure",
    icon: "Bolt",
    image: "https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&q=80",
  },
  {
    slug: "hospitality",
    title: "Hospitality",
    description: "Hotels, resorts, restaurants, entertainment venues, and leisure facilities",
    icon: "Coffee",
    image: "https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=600&q=80",
  },
];

export const PROCESS_STEPS = [
  {
    step: "01",
    title: "Submit Your Plans",
    description:
      "Upload your drawings, blueprints, or specifications. We accept all formats — PDF, CAD, Revit, and more.",
    icon: "Upload",
  },
  {
    step: "02",
    title: "Blueprint Review",
    description:
      "Our senior estimators analyze your project scope, specifications, and any RFIs to ensure complete understanding.",
    icon: "Search",
  },
  {
    step: "03",
    title: "Quantity Takeoff",
    description:
      "We perform comprehensive digital takeoffs using PlanSwift, Bluebeam, and On-Screen Takeoff for maximum accuracy.",
    icon: "Ruler",
  },
  {
    step: "04",
    title: "Cost Estimation",
    description:
      "Materials, labor, equipment, and overhead are priced using current RSMeans data and local market rates.",
    icon: "Calculator",
  },
  {
    step: "05",
    title: "Estimate Delivery",
    description:
      "You receive a detailed, formatted estimate in Excel/PDF within 24–48 hours — ready to submit for bid.",
    icon: "Send",
  },
  {
    step: "06",
    title: "Revision & Support",
    description:
      "We offer one round of free revisions and ongoing support so you can bid with complete confidence.",
    icon: "RefreshCw",
  },
];

export const TESTIMONIALS = [
  {
    name: "Michael Henderson",
    title: "CEO",
    company: "Henderson General Contracting",
    location: "Dallas, TX",
    rating: 5,
    quote:
      "BluePeak Estimation transformed how we bid projects. Their estimates are incredibly detailed and accurate — we've gone from winning 2 out of 10 bids to winning 6 out of 10. The ROI is extraordinary.",
    avatar: "MH",
  },
  {
    name: "Sarah Rodriguez",
    title: "Project Manager",
    company: "Pinnacle Construction Group",
    location: "Miami, FL",
    rating: 5,
    quote:
      "The turnaround time is remarkable. We submitted our plans on Monday morning and had a complete, professional estimate by Tuesday afternoon. The detail level rivals what we get from in-house estimators.",
    avatar: "SR",
  },
  {
    name: "James O'Brien",
    title: "Owner",
    company: "O'Brien & Sons Builders",
    location: "Chicago, IL",
    rating: 5,
    quote:
      "As a small general contractor, having access to BluePeak's expertise gives us a competitive edge we couldn't afford to hire in-house. Professional, responsive, and worth every dollar.",
    avatar: "JO",
  },
  {
    name: "David Kim",
    title: "VP of Operations",
    company: "Apex Structural Solutions",
    location: "Los Angeles, CA",
    rating: 5,
    quote:
      "The MEP estimates we get from BluePeak are used directly by our subcontractors. That says everything about the quality. Accurate, clear, and formatted exactly how we need them.",
    avatar: "DK",
  },
  {
    name: "Lisa Thompson",
    title: "Principal",
    company: "Thompson Development LLC",
    location: "Atlanta, GA",
    rating: 5,
    quote:
      "We've trusted BluePeak with over 40 projects in the last three years. They understand the construction market deeply and their numbers hold up during construction. No surprises.",
    avatar: "LT",
  },
  {
    name: "Robert Martinez",
    title: "Senior Estimator",
    company: "Northstar Commercial Builders",
    location: "Phoenix, AZ",
    rating: 5,
    quote:
      "What sets BluePeak apart is the communication. They flag issues in the drawings we missed, ask the right questions, and deliver estimates that reflect real-world conditions. Truly professional.",
    avatar: "RM",
  },
];

export const FAQ_ITEMS = [
  {
    question: "What types of construction projects do you estimate?",
    answer:
      "BluePeak Estimation covers all construction types including residential, commercial, industrial, healthcare, education, government, and infrastructure projects. We estimate all trades — from concrete and steel to MEP systems, drywall, roofing, and finishes.",
  },
  {
    question: "How fast can I receive my estimate?",
    answer:
      "Our standard turnaround is 24–48 hours for most projects. For larger, complex projects, we provide a timeline after reviewing your plans. Rush delivery (within 12 hours) is available for an additional fee.",
  },
  {
    question: "What file formats do you accept for plans?",
    answer:
      "We accept all standard formats including PDF, CAD (DWG/DXF), Revit (RVT), Bluebeam, and printed plan scans. Any format that shows the project dimensions, specifications, and scope of work.",
  },
  {
    question: "How accurate are your estimates?",
    answer:
      "Our estimates carry a 98% accuracy rate based on client feedback and project close-out data. We use RSMeans cost data, local market pricing, and current material costs to ensure every estimate reflects real-world conditions.",
  },
  {
    question: "Do you sign NDAs and confidentiality agreements?",
    answer:
      "Yes. We understand that construction plans are proprietary and sensitive. We are happy to sign NDAs and confidentiality agreements before reviewing any project documents.",
  },
  {
    question: "What software do you use for estimating?",
    answer:
      "We use industry-standard software including PlanSwift, Bluebeam Revu, On-Screen Takeoff (OST), RSMeans Online, and Microsoft Excel for deliverables. All takeoffs are digital and fully traceable.",
  },
  {
    question: "Do you offer revisions if something changes?",
    answer:
      "Yes. We include one round of revisions at no additional cost. If scope changes significantly, we will discuss pricing transparently before proceeding with additional revisions.",
  },
  {
    question: "Can you estimate just a portion of a project?",
    answer:
      "Absolutely. We can provide estimates for individual trades, specific phases, or portions of a project. We tailor the scope of work to exactly what you need.",
  },
  {
    question: "What states do you serve?",
    answer:
      "We serve contractors and developers across all 50 US states. Our team is familiar with regional labor rates, material costs, and local market conditions in major markets including New York, Los Angeles, Chicago, Houston, Phoenix, and beyond.",
  },
  {
    question: "How do I get started?",
    answer:
      "Simply contact us via our Get Free Estimate form, email, or phone. Upload your plans, describe your project, and we'll send you a proposal within a few hours. No commitment required for the initial review.",
  },
];

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
  image: string;
  img: string;
  featured: boolean;
  author: string;
  authorImg: string;
  tags: string[];
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "how-to-win-more-construction-bids",
    title: "How to Win More Construction Bids with Accurate Estimating",
    excerpt: "Winning construction bids isn't just about being the lowest number — it's about being the most credible and accurate. Here's how professional estimating gives you the edge.",
    category: "Bidding Strategy",
    date: "2026-06-15",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
    img: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
    featured: true,
    author: "James Hartwell",
    authorImg: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&auto=format&fit=crop",
    tags: ["Estimating", "Bidding", "Strategy"],
  },
  {
    slug: "construction-material-takeoff-guide",
    title: "The Complete Guide to Construction Material Takeoffs",
    excerpt: "A thorough material takeoff is the foundation of every accurate construction estimate. Learn the process, common mistakes, and how to ensure nothing is missed.",
    category: "Estimating Guide",
    date: "2026-06-08",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
    img: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Takeoff", "Materials", "Guide"],
  },
  {
    slug: "mep-estimating-best-practices",
    title: "MEP Estimating Best Practices for Commercial Projects",
    excerpt: "Mechanical, electrical, and plumbing estimates are among the most complex in construction. Discover the standards and methods that keep MEP bids competitive.",
    category: "MEP Estimating",
    date: "2026-05-28",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80",
    img: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&q=80",
    featured: false,
    author: "David Okafor",
    authorImg: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop",
    tags: ["MEP", "Estimating", "Commercial"],
  },
  {
    slug: "outsourcing-construction-estimating",
    title: "Why Contractors Are Outsourcing Their Estimating — and Winning",
    excerpt: "Outsourcing construction estimating isn't a shortcut — it's a strategic advantage. Discover how leading contractors are cutting costs and improving bid accuracy.",
    category: "Industry Trends",
    date: "2026-05-20",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    img: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    featured: false,
    author: "Emily Chen",
    authorImg: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop",
    tags: ["Outsourcing", "Trends", "Strategy"],
  },
  {
    slug: "construction-cost-estimation-software",
    title: "Top Construction Cost Estimation Software in 2026",
    excerpt: "From PlanSwift to RSMeans, we break down the industry's leading estimating tools — what they do best, and which trade they're built for.",
    category: "Technology",
    date: "2026-05-10",
    readTime: "9 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    img: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    featured: false,
    author: "Sarah Montoya",
    authorImg: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop",
    tags: ["Technology", "Software", "Tools"],
  },
  {
    slug: "residential-construction-cost-per-square-foot",
    title: "Residential Construction Cost Per Square Foot in 2026",
    excerpt: "Construction costs vary wildly by state, material, and project type. This guide breaks down what to expect for residential projects across major US markets.",
    category: "Cost Data",
    date: "2026-05-01",
    readTime: "11 min read",
    image: "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&q=80",
    img: "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&q=80",
    featured: false,
    author: "James Hartwell",
    authorImg: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&auto=format&fit=crop",
    tags: ["Cost Data", "Residential", "Pricing"],
  },
  // --- Migrated from old blogData.js ---
  {
    slug: "home-construction-estimator",
    title: "What Is a Home Construction Estimator? Complete Guide to Building Costs",
    excerpt: "Learn everything about home construction estimating—budgeting, cost calculators, estimating tools, regional price ranges, and expert tips to avoid mistakes.",
    category: "Estimating Guide",
    date: "April 2026",
    readTime: "14 min read",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Home Construction", "Estimating", "Budgeting"],
  },
  {
    slug: "how-to-estimate-new-construction-plumbing-cost",
    title: "How to Estimate New Construction Plumbing Cost: A Comprehensive Guide",
    excerpt: "Let's delve deeper into the process of how to estimate new construction plumbing costs. We will outline the essential tips and tools to overcome the financial burdens of the plumbing system.",
    category: "MEP Estimating",
    date: "April 2026",
    readTime: "16 min read",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80",
    img: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Plumbing", "MEP", "New Construction"],
  },
  {
    slug: "how-to-do-a-masonry-estimate",
    title: "How to Do a Masonry Estimate: A Step-by-Step Guide",
    excerpt: "It is a skillful and artful task that requires mindful planning and scheduling with technical support. Learn the complete process.",
    category: "Estimating Guide",
    date: "April 2026",
    readTime: "14 min read",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
    img: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Masonry", "Estimating", "Construction"],
  },
  {
    slug: "how-to-estimate-electrical-work",
    title: "How to Estimate Electrical Work [7 Easy Steps]",
    excerpt: "Learn how to estimate electrical work accurately for any project. Use this proven 7-step process to estimate electrical work fast and accurately.",
    category: "MEP Estimating",
    date: "April 2026",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80",
    img: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Electrical", "MEP", "Estimating"],
  },
  {
    slug: "estimate-the-cost-of-a-commercial-building",
    title: "How Do You Estimate the Cost of a Commercial Building?",
    excerpt: "Learn how to accurately estimate the cost of a commercial building. Our guide covers materials, labor, permits, design fees, and methods to stay on budget.",
    category: "Cost Data",
    date: "April 2026",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    img: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Commercial", "Cost Estimating", "Construction"],
  },
  {
    slug: "replacement-plumbing-cost-in-an-old-house",
    title: "Replacement Plumbing Cost in an Old House: Complete Estimator's Guide",
    excerpt: "Understand the replacement plumbing cost in an old house. This guide covers material, labor, permits, and factors to estimate projects.",
    category: "MEP Estimating",
    date: "April 2026",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80",
    img: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Plumbing", "Renovation", "Estimating"],
  },
  {
    slug: "how-to-do-drywall-takeoff",
    title: "How to Do Drywall Takeoff | Step-by-Step Guide 2026",
    excerpt: "Learn how to do drywall takeoff accurately. Follow our step-by-step guide to estimate materials, costs, and waste. Read this guide to know more.",
    category: "Estimating Guide",
    date: "April 2026",
    readTime: "16 min read",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    img: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Drywall", "Takeoff", "Estimating"],
  },
  {
    slug: "reliable-estimation-company-in-the-usa",
    title: "How to Find a Reliable Estimation Company in the USA",
    excerpt: "Navigating construction project costs? Learn how to find a reliable estimation company in the USA. Discover key factors like experience, certifications, and technology use.",
    category: "Industry Trends",
    date: "April 2026",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    img: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    featured: false,
    author: "BluePeak Team",
    authorImg: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop",
    tags: ["Estimating", "Company", "Guide"],
  },
  // ============ 15-24. NEW BLOG POSTS ============
  {
    slug: "how-much-does-a-construction-estimate-cost",
    title: "How Much Does a Professional Construction Estimate Cost in 2025?",
    excerpt: "Wondering how much a construction estimate costs? We break down pricing by project type, size, and trade. Get transparent fees for professional estimating services.",
    category: "Estimating Costs",
    date: "2025-01-15",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["construction estimate cost","estimating fees","takeoff pricing","professional estimator cost"],
  },
  {
    slug: "mep-estimating-services",
    title: "What Is MEP Estimating and Why Every Contractor Needs It",
    excerpt: "Learn what MEP estimating services are and why mechanical, electrical, and plumbing costs make up 25-40% of total construction cost. Avoid costly estimating errors.",
    category: "MEP Estimating",
    date: "2025-02-10",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["MEP estimating services","mechanical estimating","electrical estimating","plumbing estimating"],
  },
  {
    slug: "construction-takeoff-services",
    title: "Construction Takeoff Services: The Complete Guide for Contractors",
    excerpt: "Learn what construction takeoff services include, manual vs digital methods, and how outsourcing reduces errors by 85%. Complete guide for general and specialty contractors.",
    category: "Estimating Services",
    date: "2025-03-05",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["construction takeoff services","quantity takeoff","digital takeoff","takeoff outsourcing"],
  },
  {
    slug: "how-to-win-more-construction-bids-2025",
    title: "7 Proven Strategies to Win More Construction Bids in 2025",
    excerpt: "Want to win more construction bids? Learn 7 proven strategies backed by industry data that can improve your win rate by 15-20%. Includes estimating, speed, and relationship tips.",
    category: "Bidding Strategy",
    date: "2025-04-01",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["win more construction bids","bidding strategy","construction bid tips","bid management"],
  },
  {
    slug: "residential-construction-estimating",
    title: "Residential Construction Estimating: A Complete Guide for Home Builders",
    excerpt: "Master residential construction estimating with this complete guide for home builders. Learn cost-per-square-foot methods, common mistakes, and how NAHB data can improve accuracy.",
    category: "Residential",
    date: "2025-05-12",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["residential construction estimating","home building costs","cost per square foot house","residential estimator"],
  },
  {
    slug: "commercial-construction-cost-estimating",
    title: "Commercial Construction Cost Estimating: What Every Developer Should Know",
    excerpt: "Learn commercial construction cost estimating essentials for developers. CSI divisions, value engineering strategies, and CFMA-backed budget management techniques for profitable projects.",
    category: "Commercial",
    date: "2025-06-18",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["commercial construction cost estimating","developer cost guide","CSI divisions","value engineering construction"],
  },
  {
    slug: "concrete-estimating-services",
    title: "Concrete Estimating Services: How to Get Accurate Costs for Your Project",
    excerpt: "Professional concrete estimating services help contractors price foundations, slabs, walls, and more with ACI-backed accuracy. Learn cost factors and common estimating errors to avoid.",
    category: "Concrete",
    date: "2025-07-08",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["concrete estimating services","concrete cost estimating","concrete takeoff","flatwork estimating"],
  },
  {
    slug: "electrical-estimating-services",
    title: "Electrical Estimating Services: Everything Contractors Need to Know",
    excerpt: "Learn what electrical estimating services include, how to split labor vs material costs, and why NECA manual standards and RSMeans data improve accuracy for commercial and residential work.",
    category: "MEP Estimating",
    date: "2025-08-14",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["electrical estimating services","electrical takeoff","NECA estimating","commercial electrical estimating"],
  },
  {
    slug: "construction-cost-per-square-foot-usa",
    title: "Construction Cost Per Square Foot in the USA: 2025 State-by-State Guide",
    excerpt: "Compare construction cost per square foot across all 50 US states. 2025 RSMeans data shows regional differences from $110 in the South to $420+ in high-cost metro areas.",
    category: "Cost Data",
    date: "2025-09-22",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["construction cost per square foot USA","state construction costs","RSMeans cost data","regional building costs"],
  },
  {
    slug: "outsource-construction-estimating",
    title: "Why Smart Contractors Outsource Construction Estimating (And How to Do It Right)",
    excerpt: "Learn why leading contractors outsource construction estimating for 40-60% cost savings, faster turnaround, and better accuracy. FMI-backed guide with step-by-step outsourcing tips.",
    category: "Industry Trends",
    date: "2025-10-03",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["outsource construction estimating","estimating outsourcing","construction estimating services","bid preparation outsourcing"],
  },
  // ============ 25-34. NEW TRADE BLOG POSTS ============
  {
    slug: "roofing-estimating-services",
    title: "Roofing Estimating Services: How to Get Accurate Costs Before You Bid",
    excerpt: "Professional roofing estimating services help contractors nail material takeoffs, labor costs, and profit margins. Learn how accurate estimates win more bids and boost revenue.",
    category: "Trade Estimating",
    date: "2025-02-03",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["roofing estimating services","roofing takeoff","construction estimating","roof cost estimator"],
  },
  {
    slug: "drywall-estimating-services",
    title: "Drywall Estimating Services: Stop Losing Money on Every Job",
    excerpt: "Drywall estimating services eliminate the underbidding trap that costs contractors thousands. Discover how accurate sheet counts, finishing levels, and labor rates protect your margins.",
    category: "Trade Estimating",
    date: "2025-02-17",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["drywall estimating services","drywall takeoff","construction estimating","drywall cost"],
  },
  {
    slug: "hvac-estimating-services",
    title: "HVAC Estimating Services: A Complete Guide for Mechanical Contractors",
    excerpt: "HVAC estimating services help mechanical contractors accurately price equipment, ductwork, and installation labor. Learn how professional takeoffs boost win rates and protect margins.",
    category: "Trade Estimating",
    date: "2025-03-04",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["HVAC estimating services","mechanical estimating","HVAC takeoff","construction estimating"],
  },
  {
    slug: "plumbing-estimating-services",
    title: "Plumbing Estimating Services: How Accurate Takeoffs Help You Win More Bids",
    excerpt: "Plumbing estimating services deliver precise fixture counts, pipe quantities, and labor units. Learn how professional takeoffs eliminate guesswork and boost your bid win rate.",
    category: "Trade Estimating",
    date: "2025-03-18",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["plumbing estimating services","plumbing takeoff","construction estimating","plumbing cost estimator"],
  },
  {
    slug: "framing-estimating-services",
    title: "Framing Estimating Services: Lumber Takeoffs That Actually Match Reality",
    excerpt: "Framing estimating services deliver accurate board foot counts, lumber pricing, and labor calculations. Learn how pro takeoffs handle volatile material costs and complex roof framing.",
    category: "Trade Estimating",
    date: "2025-04-01",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["framing estimating services","lumber takeoff","construction estimating","framing cost estimator"],
  },
  {
    slug: "masonry-estimating-services",
    title: "Masonry Estimating Services: Get Your Brick, Block and Stone Bids Right",
    excerpt: "Masonry estimating services deliver accurate unit counts, mortar calculations, and labor rates for brick, CMU, and stone. Discover how pro estimators eliminate costly bid errors.",
    category: "Trade Estimating",
    date: "2025-04-15",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["masonry estimating services","masonry takeoff","construction estimating","brick and block estimating"],
  },
  {
    slug: "flooring-estimating-services",
    title: "Flooring Estimating Services: Why Accurate Takeoffs Are Critical for Flooring Contractors",
    excerpt: "Flooring estimating services help contractors price LVP, hardwood, tile, carpet, and epoxy with precision. Discover how accurate takeoffs eliminate costly waste and protect your margins.",
    category: "Trade Estimating",
    date: "2025-05-06",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["flooring estimating services","flooring takeoff","construction estimating","flooring cost estimator"],
  },
  {
    slug: "painting-estimating-services",
    title: "Painting Estimating Services: How to Price Every Job With Confidence",
    excerpt: "Painting estimating services help contractors price interior, exterior, and commercial work accurately. Discover how surface prep, paint grades, and labor rates affect your bottom line.",
    category: "Trade Estimating",
    date: "2025-05-20",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["painting estimating services","painting takeoff","construction estimating","painting cost estimator"],
  },
  {
    slug: "sitework-estimating-services",
    title: "Sitework Estimating Services: Earthwork and Site Prep Costs Explained",
    excerpt: "Sitework estimating services help contractors price grading, excavation, utilities, paving, and retaining walls. Learn how accurate takeoffs protect margins on site development projects.",
    category: "Trade Estimating",
    date: "2025-06-03",
    readTime: "10 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["sitework estimating services","earthwork estimating","site development","construction estimating"],
  },
  {
    slug: "insulation-estimating-services",
    title: "Insulation Estimating Services: R-Values, Materials and Real Costs for Contractors",
    excerpt: "Insulation estimating services help contractors price batt, spray foam, rigid, and blown-in insulation accurately. Learn how R-value requirements and energy codes affect your bids.",
    category: "Trade Estimating",
    date: "2025-06-17",
    readTime: "9 min read",
    image: "/blog_pic.png",
    img: "/blog_pic.png",
    featured: false,
    author: "BluePeak Estimation Team",
    authorImg: "/blog_pic.png",
    tags: ["insulation estimating services","insulation takeoff","construction estimating","insulation cost estimator"],
  },
];

export const PROJECTS = [
  {
    title: "Downtown Mixed-Use Tower",
    location: "New York, NY",
    trade: "Commercial",
    value: "$48M",
    sqft: "320,000 sq ft",
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    description: "52-story mixed-use development including retail, office, and residential components. Full MEP, concrete, and steel estimation.",
  },
  {
    title: "Regional Medical Center Expansion",
    location: "Houston, TX",
    trade: "Healthcare",
    value: "$22M",
    sqft: "95,000 sq ft",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    description: "Phased hospital expansion covering surgical suites, imaging center, and patient tower. Full MEP and specialty systems estimation.",
  },
  {
    title: "Industrial Distribution Campus",
    location: "Dallas, TX",
    trade: "Industrial",
    value: "$15M",
    sqft: "500,000 sq ft",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80",
    description: "Multi-building industrial campus with dock-high warehousing, office build-out, and full site development.",
  },
  {
    title: "Highway Interchange Reconstruction",
    location: "Los Angeles, CA",
    trade: "Civil",
    value: "$35M",
    sqft: "4.2 miles",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    description: "Complex highway reconstruction including bridge replacement, retaining walls, storm drainage, and full earthwork analysis.",
  },
  {
    title: "Luxury Residential Community",
    location: "Miami, FL",
    trade: "Residential",
    value: "$8.5M",
    sqft: "180,000 sq ft",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80",
    description: "120-unit luxury condominium development with pools, amenities, and underground parking. Full trades estimation.",
  },
  {
    title: "University Science Building",
    location: "Chicago, IL",
    trade: "Education",
    value: "$28M",
    sqft: "145,000 sq ft",
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    description: "State-of-the-art research and laboratory facility requiring specialized MEP, clean room, and data center estimation.",
  },
];

export const NAV_LINKS = [
  { label: "Home", href: "/" },
  {
    label: "Services",
    href: "/services",
    children: [
      { label: "All Services", href: "/services", description: "Complete estimating services" },
      { label: "Construction Estimating", href: "/services/construction-estimating", description: "Full project cost estimates" },
      { label: "Material Takeoff", href: "/services/material-takeoff", description: "Quantity takeoff from plans" },
      { label: "MEP Estimation", href: "/services/mep-estimation", description: "Mechanical, electrical, plumbing" },
      { label: "Civil Estimation", href: "/services/civil-estimation", description: "Earthwork & infrastructure" },
      { label: "Commercial Estimation", href: "/services/commercial-estimation", description: "Office, retail & more" },
      { label: "Residential Estimation", href: "/services/residential-estimation", description: "Homes & multi-family" },
    ],
  },
  { label: "Industries", href: "/industries" },
  { label: "Projects", href: "/projects" },
  { label: "About", href: "/about" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];
